databases:
  - name: nexutest_production
    databaseName: nexutest_production
    user: nexutest
    plan: free

services:
  - type: web
    name: nexutest
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexutest_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2